### ISSUE TITLE
Can use Json.Net instead of JavaScriptSerailizer

### ISSUE THREAD

**Issue by wali007hamza** [daulet/Echo#1]
It's faster and more efficient.

**Comment by daulet** [comment]
I'll consider it after I have performance results for current implementation. It might turn out that using JavaScriptSerializer is more efficient for this framework's purposes, but I want to make that decision based on actual results, not on a common believe that one implementation is "more efficient" than other.

**Comment by daulet** [comment]
Fixed in #23
