### ISSUE TITLE
Possible improvement in reading from StreamReader

### ISSUE THREAD

**Issue by wali007hamza** [daulet/Echo#2]
Echo/samples/MultiDependency/Program.cs - Test(). I know this is just a sample but assuming this is how you'll be using this in actual code.

When you pass in the stream reader, does this mean that you'll be reading all the saved traffic. Even if you use EchoReader which I am implementing for Ols, I can't give you refined data. Because I correlate everything using correlationId. Now at the time of running UTs either we go through all the saved traffic or have some functionality to pin point the data that we need.

I think one way to solve this problem is that you pass me the target interface while you write via EchoWriter. And before running the test, the test player or stream reader takes in the list of interfaces that you want to test against. While downloading the traffic from the service or anywhere we can use some classification to index the files based on Interfaces required. 

Or maybe you've already thought of this before and have a better solution ?

**Comment by daulet** [comment]
Addressed with #22
